name: Build (Arch Linux)

on: [push, pull_request]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  build-linux-gcc:
    name: Arch Linux (GCC Latest)
    runs-on: ubuntu-latest  # Uses an Ubuntu runner with an Arch Linux container
    container: archlinux:latest  # Runs the job inside an Arch Linux container

    steps:
      - name: Install Dependencies
        run: |
          pacman -Sy --noconfirm base-devel cmake ninja gcc git ncurses

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure CMake
        shell: bash
        env:
          CC: gcc
          CXX: g++
        run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja

      - name: Build Project
        shell: bash
        run: cmake --build . -j$(nproc)

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: compiled-executable
          path: ./text-editor
